name: "Tom's Site"
favicon: null
layout_spectrum: 0.28390135103836656
typography_spectrum: 0.852868115529418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4913742383942008
  lightness: 0.767367230495438
  saturation: 0.4626705530099571
  rhythmicContrast: 0.833450163481757
purpose: []
